---
title: Drupal 6 is SLOW
author: Anthony Quoc Anh Doan
date: '2009-09-20'
slug: drupal-6-is-slow
categories:
  - Web Development
tags:
  - PHP
  - Drupal
description: ~
image: Drupal_Logo_Horizontal_Blue.svg 
math: ~
license: ~
hidden: no
comments: yes
---

**Note:** This post was created awhile back on another platform and I migrated to my current one.

## Drupal 6 Performance Issues and Optimization  

Drupal 6 is incredibly slow right now. Adam and I just installed a lot of modules and enabled them.  

### Setup  
*Debian 5 with Apache 2*  

### 1st Assumption: Database  
Accessing the database could be the reason for the slowdown. Checking the MySQL logs (`/var/log`) reveals nothing—perhaps I didn’t enable logging. I’ll check on that later.  

### 2nd Assumption: Modules  
Let's disable all the modules! This helped just a little. During this process, I also disabled all caching options in Drupal.  

### A Surprising Discovery  
After taking a day-long break, I checked the website again, and it was fast! However, when clicking on the administration URL, it was still very slow. Here's what I found on the Drupal support forum:  

> *"The admin pages in Drupal 6 are slow because they perform a lot of housekeeping and rebuilding (thousands of queries, as you noticed, and these are not just cosmetic). Caching probably won’t help with that.*  
>  
> *If it is unworkable, disabling the update status module will probably help a bit. There are open issues for reducing the number of queries in future updates, but don’t expect the D6 admin pages to become snappy. They take the hit for some tasks that make the user part of the site more reliable.*  
>  
> *About the normal site pages... the usual optimization methods should apply."*  
>  
> — [cog.rusty](http://drupal.org/user/33697), February 21, 2009  

### Optimization Steps  
Alright, let’s optimize the webpage.  

#### Installed Tools:  
- [Life-of-Request Info extension](https://addons.mozilla.org/extensions/moreinfo.php?application=firefox&category=Developer%20Tools&numpg=10&id=1743)  
- [Devel module](http://drupal.org/project/devel) (Where is this log file?)  

#### 1st Optimization: PHP Optimization with APC  
I installed the **APC** package for PHP (read about it [here](http://pecl.php.net/package/APC)).  
Here’s a tutorial on using **APC**:  
[APC on Debian Lenny](http://www.easywebdns.com/tutorials/Linux/php/APC_ON_DEBIAN_LENNY)  

#### Performance Results:  
**Accessing main Drupal as webmaster:**  
- 1st try: **1.3s**  
- 2nd try (browser cache cleared): **0.661s**  
- 3rd try: **0.877s**  

**As a non-user:**  
- **0.536s**  

### Enabling All Modules  
- **Main page:** **1.114s - 1.124s**  
- **Content-generated pages:** ~**0.224s**, at most **< 0.5s** (no images, just text)  

**Yay, it’s faster!** 🚀
